tap "1password/tap"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "jandedobbeleer/oh-my-posh"

brew "bat"
brew "coreutils"
brew "curl"
brew "dnsmasq"
brew "eza"
brew "fzf"
brew "git"
brew "gnupg"
brew "grep"
brew "lazygit"
brew "lsd"
brew "mas"
brew "neovim"
brew "nvm"
brew "oh-my-posh"
brew "pkg-config"
brew "rsync"
brew "stow"
brew "tmux"
brew "tree"
brew "zoxide"
brew "zsh"
brew "jandedobbeleer/oh-my-posh/oh-my-posh", link: false

cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "affinity-photo"
cask "alacritty"
cask "alfred"
cask "bettertouchtool"
cask "bruno"
cask "daisydisk"
cask "discord"
cask "firefox@developer-edition"
cask "font-hack-nerd-font"
cask "font-lato"
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "google-chrome"
cask "microsoft-teams"
cask "phpstorm"
cask "sequel-ace"
cask "slack"
cask "synology-drive"
cask "telegram"
cask "transmit"
cask "ubersicht"

# Mac App Store
mas "Calca", id: 635758264
mas "Harvest", id: 506189836
mas "Microsoft Remote Desktop", id: 1295203466
mas "Things", id: 904280696
mas "Velja", id: 1607635845
mas "WireGuard", id: 1451685025
